### ISSUE TITLE
Using returned string as chart title

### ISSUE THREAD

**Issue by adrian-carrio** [shapelets/shapelets-solo-examples#16]
When using a custom function that returns a string, using the returned string as title for a chart does not work.

**Comment by josesaranda** [comment]
It isn't a bug, It is a feature not implemented yet.

**Comment by josesaranda** [comment]
Stay tuned to the next shapelets-solo version. This feature will be available soon!

**Comment by josesaranda** [comment]
Works in  `shapelets-solo==0.3.15`
