### ISSUE TITLE
Drawing views on computed sequences

### ISSUE THREAD

**Issue by adrian-carrio** [shapelets/shapelets-solo-examples#18]
Currently it is not possible to draw views on computed sequences. This is a relevant feature, as sequences are not always loaded just ready to be plotted and might require some pre-processing or they might simply depend on other sequences.

You can check the following [example](https://github.com/shapelets/shapelets-solo-examples/blob/data-science/dataapps/Use-cases/01_anomaly_search_in_stocks_correlation.py) where this functionality is required.

**Comment by josesaranda** [comment]
This feature works now in `shapelets-solo==0.3.15`
