### ISSUE TITLE
Plotted data disappears when scrolling over charts

### ISSUE THREAD

**Issue by adrian-carrio** [shapelets/shapelets-solo-examples#19]
When plotting some sequences while charts are visible, the plotted data is displayed correctly. However, if the user scrolls up or down and the charts leave the view, the data is no longer visible when you return to them. This bug should be reproducible in the following [example](https://github.com/shapelets/shapelets-solo-examples/blob/data-science/dataapps/Use-cases/01_anomaly_search_in_stocks_correlation.py).

**Comment by josesaranda** [comment]
Thanks to report this issue. Stay tuned to the next shapelets-solo version.

**Comment by josesaranda** [comment]
Fixed in `shapelets-solo==0.3.15`
