### ISSUE TITLE
Feature request: clearing / enabling / disabling browser cache

### ISSUE THREAD

**Issue by adrian-carrio** [shapelets/shapelets-solo-examples#26]
Is it possible to include a button that clears up the browser cache or that completely disables browser cache? This could be very helpful in cases where results should not be cached, like randomized simulations.

Here is a relevant discussion that could be helpful to implement this feature: https://stackoverflow.com/questions/1922910/force-browser-to-clear-cache

**Comment by josesaranda** [comment]
This improvement is not related to the browser cache. shapelets-solo platform provides tools to ensure your algorithms are accelerated by a cache system. The most of times this feature works really really well and only the first time that your algorithm is executed takes the full time, the next time the system checks if it has stored the result for the provided entry parameters and if it has it throws you the previous executed result.

Anyway, thank you for find this issue (related by our server system cache). I'm going to open another ticket according to the real issue.

**Comment by josesaranda** [comment]
Thanks for reporting the problem. I think is properly to follow the real issue [here](https://github.com/shapelets/shapelets-solo-examples/issues/28)
