### ISSUE TITLE
Feature request: quick deletion of multiple dataapps / collections / sequences

### ISSUE THREAD

**Issue by adrian-carrio** [shapelets/shapelets-solo-examples#27]
When dealing with large amounts of datapps, collections and sequences, the following features would be desirable:
-Clearing all datapps, collections and/or sequences with a single click.
-Deleting collections directly from the collections page. Now it is required to go inside each of the collections to delete it.
-Deleting individual sequences within a collection.
-Selecting two or more dataapps, collections or sequences in order to delete them.

Depending on how you plan to address it, this feature request can be splitted into multiple issues.

**Comment by avilchess** [comment]
This feature is supported in shapelets-solo 0.4.0
