### ISSUE TITLE
Feature request: clearing / enabling / disabling system cache

### ISSUE THREAD

**Issue by josesaranda** [shapelets/shapelets-solo-examples#28]
The cache provided by shapelets-solo server ensure the algorithm acceleration; for the same parameters it expects the same result, but sometimes the algorithms could response with another different result if it depends on random values, or timestamps.

Could be interesting to provide to shapelets-solo and cristal-ui tools to clear, enable or disable the shapelets-solo server system cache.

**Comment by avilchess** [comment]
This feature is supported in shapelets-solo 0.4.0
