### ISSUE TITLE
Feature request: function to plot histograms

### ISSUE THREAD

**Issue by adrian-carrio** [shapelets/shapelets-solo-examples#36]
It would be nice to have a function to automatically compute and plot histograms, similar to PyPlot's [hist](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html).
This function should be able to receive at least a numpy array/NDArray and optionally, the number of desired bins for the histogram.

**Comment by avilchess** [comment]
shapelets-solo 0.4.0 includes this component
