### ISSUE TITLE
Feature request: controller for combobox

### ISSUE THREAD

**Issue by adrian-carrio** [shapelets/shapelets-solo-examples#7]
It would be very useful to be able to instantiate and place comboboxes in data apps. This will allow to choose from a list of predefined values, as in the following image:

![image](https://user-images.githubusercontent.com/86968261/124725682-f64c7080-df04-11eb-8704-0ebeab068a8c.png)

**Comment by josesaranda** [comment]
This feature request is WIP, please stay tuned to the next release.

**Comment by josesaranda** [comment]
This feature works right now under shapelets-solo v0.3.8 and above!
